import assert from 'node:assert/strict';
import {mkdtemp, readFile, writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {publishRelease} from '../../deploy/publish-release.mjs';

const sha256 = async p => (await import('node:crypto')).createHash('sha256').update(await readFile(p)).digest('hex');
async function setup(){const root=await mkdtemp(path.join(tmpdir(),'publisher-'));const apk=path.join(root,'incoming.apk');await writeFile(apk,'one');const meta={schemaVersion:1,channel:'internal',versionName:'1.0.0',versionCode:1,applicationId:'com.hermes.remote',publishedAt:'2026-01-01T00:00:00Z',fileName:'Hermes-Remote-1.0.0-debug.apk',downloadUrl:'https://mrlgs.net/releases/Hermes-Remote-1.0.0-debug.apk',sizeBytes:3,sha256:await sha256(apk),certificateSha256:'06c18dfc4a852330654c2da040a578bccab13b71dde4ac962bb9bc2271dd32c5',minSdk:26,releaseNotes:['first'],sourceCommit:'abc'};return{root,apk,meta};}
test('first publish, append, sorting/latest and idempotency',async()=>{const s=await setup();await publishRelease(s.root,s.apk,s.meta);await publishRelease(s.root,s.apk,s.meta);const apk2=path.join(s.root,'two.apk');await writeFile(apk2,'two');await publishRelease(s.root,apk2,{...s.meta,versionName:'1.0.1',versionCode:2,fileName:'Hermes-Remote-1.0.1-debug.apk',downloadUrl:'https://mrlgs.net/releases/Hermes-Remote-1.0.1-debug.apk',sha256:await sha256(apk2)});const i=JSON.parse(await readFile(path.join(s.root,'index.json'),'utf8'));assert.deepEqual(i.versions.map(v=>v.versionCode),[2,1]);assert.equal(i.latestVersionCode,2);});
test('rejects size/hash and version identity conflicts without changing index',async()=>{const s=await setup();await publishRelease(s.root,s.apk,s.meta);const before=await readFile(path.join(s.root,'index.json'),'utf8');for(const bad of [{...s.meta,sizeBytes:4},{...s.meta,sha256:'b'.repeat(64)}]) await assert.rejects(publishRelease(s.root,s.apk,bad));const conflicting=path.join(s.root,'conflicting.apk');await writeFile(conflicting,'different');await assert.rejects(publishRelease(s.root,conflicting,{...s.meta,sizeBytes:9,sha256:await sha256(conflicting),versionName:'1.0.1',fileName:'Hermes-Remote-1.0.1-debug.apk',downloadUrl:'https://mrlgs.net/releases/Hermes-Remote-1.0.1-debug.apk'}),/version conflict/);assert.equal(await readFile(path.join(s.root,'index.json'),'utf8'),before);});
test('idempotent publish repairs a missing or corrupt target APK',async()=>{const s=await setup();await publishRelease(s.root,s.apk,s.meta);const target=path.join(s.root,s.meta.fileName);await writeFile(target,'bad');await publishRelease(s.root,s.apk,s.meta);assert.equal(await readFile(target,'utf8'),'one');});
test('concurrent different versions preserve both entries and previous index',async()=>{const s=await setup();const apk2=path.join(s.root,'two.apk');await writeFile(apk2,'two');const second={...s.meta,versionName:'1.0.1',versionCode:2,fileName:'Hermes-Remote-1.0.1-debug.apk',downloadUrl:'https://mrlgs.net/releases/Hermes-Remote-1.0.1-debug.apk',sha256:await sha256(apk2)};await Promise.all([publishRelease(s.root,s.apk,s.meta),publishRelease(s.root,apk2,second)]);const index=JSON.parse(await readFile(path.join(s.root,'index.json'),'utf8'));assert.deepEqual(index.versions.map(v=>v.versionCode),[2,1]);const previous=JSON.parse(await readFile(path.join(s.root,'index.json.prev'),'utf8'));assert.equal(previous.versions.length,1);});
test('concurrent identical publish is idempotent and full entry changes conflict',async()=>{const s=await setup();await Promise.all([publishRelease(s.root,s.apk,s.meta),publishRelease(s.root,s.apk,s.meta)]);await assert.rejects(publishRelease(s.root,s.apk,{...s.meta,releaseNotes:['changed']}),/version conflict/);const index=JSON.parse(await readFile(path.join(s.root,'index.json'),'utf8'));assert.equal(index.versions.length,1);});
