import assert from 'node:assert/strict';
import test from 'node:test';
import {validateIndex,validateVersion} from '../src/schema.mjs';

const version={versionName:'1.2.3',versionCode:3,applicationId:'com.hermes.remote',channel:'internal',publishedAt:'2026-01-01T00:00:00Z',fileName:'Hermes-Remote-1.2.3-debug.apk',downloadUrl:'https://mrlgs.net/releases/Hermes-Remote-1.2.3-debug.apk',sizeBytes:3,sha256:'a'.repeat(64),certificateSha256:'06c18dfc4a852330654c2da040a578bccab13b71dde4ac962bb9bc2271dd32c5',minSdk:26,releaseNotes:['x'],sourceCommit:'abcdef1'};
const index=versions=>({schemaVersion:1,channel:'internal',latestVersionCode:versions[0]?.versionCode??0,generatedAt:'2026-01-01T00:00:00Z',versions});
test('accepts default and explicit 443 release URL',()=>{validateVersion(version);validateVersion({...version,downloadUrl:'https://mrlgs.net:443/releases/Hermes-Remote-1.2.3-debug.apk'});});
test('rejects filename and URL injection variants',()=>{for(const change of [{versionName:'1.2'},{fileName:'evil\r\n.apk'},{downloadUrl:'https://mrlgs.net:444/releases/Hermes-Remote-1.2.3-debug.apk'},{downloadUrl:'https://u@mrlgs.net/releases/Hermes-Remote-1.2.3-debug.apk'},{downloadUrl:'https://mrlgs.net/releases/Hermes-Remote-1.2.3-debug.apk?q=1'},{downloadUrl:'https://mrlgs.net/releases/Hermes-Remote-1.2.3-debug.apk#x'}])assert.throws(()=>validateVersion({...version,...change}));});
test('index requires uniqueness descending order and correct latest',()=>{const older={...version,versionName:'1.2.2',versionCode:2,fileName:'Hermes-Remote-1.2.2-debug.apk',downloadUrl:'https://mrlgs.net/releases/Hermes-Remote-1.2.2-debug.apk'};validateIndex(index([version,older]));validateIndex(index([]));assert.throws(()=>validateIndex({...index([older,version]),latestVersionCode:3}));assert.throws(()=>validateIndex(index([version,{...older,versionCode:3}])));assert.throws(()=>validateIndex({...index([version]),latestVersionCode:2}));});
test('strictly rejects wrong scalar types and identity',()=>{for(const change of [{versionCode:'3'},{sizeBytes:'3'},{minSdk:26.1},{releaseNotes:'x'},{sourceCommit:3},{channel:'stable'},{certificateSha256:'b'.repeat(64)}])assert.throws(()=>validateVersion({...version,...change}));});
test('limits notes, versions, control characters and requires canonical UTC',()=>{for(const releaseNotes of [Array(21).fill('x'),[''],['bad\nnote'],['x'.repeat(501)]])assert.throws(()=>validateVersion({...version,releaseNotes}));assert.throws(()=>validateVersion({...version,publishedAt:'2026-01-01T08:00:00+08:00'}));assert.throws(()=>validateIndex(index(Array.from({length:101},(_,i)=>({...version,versionName:`2.0.${100-i}`,versionCode:101-i,fileName:`Hermes-Remote-2.0.${100-i}-debug.apk`,downloadUrl:`https://mrlgs.net/releases/Hermes-Remote-2.0.${100-i}-debug.apk`})))));});
