package com.hermes.client.ui.sessions

import com.hermes.client.data.error.AppError
import com.hermes.client.data.error.AppErrorCode
import com.hermes.client.data.network.GatewayRpcException

// Upstream `projects.*` error codes. Every projects handler is generated by the same factory
// (tui_gateway/server.py `_projects_method`), so these three cover the whole surface.
private const val RPC_PROJECTS_FAILED = 5061
private const val RPC_NO_SUCH_PROJECT = 5062
private const val RPC_BAD_ARGUMENT = 5063

/** Maps a failed project create/rename/folder/delete RPC to a registered product error. */
fun projectEditError(error: Throwable, stage: String): AppError {
    val code = when ((error as? GatewayRpcException)?.code) {
        RPC_NO_SUCH_PROJECT -> AppErrorCode.PROJECT_NOT_FOUND
        RPC_BAD_ARGUMENT -> AppErrorCode.PROJECT_NAME_INVALID
        else -> AppErrorCode.PROJECT_SAVE_FAILED
    }
    return AppError(
        code = code,
        // A missing project and a rejected name are both terminal: retrying the identical call
        // cannot succeed. Only the unmapped bucket is worth another attempt.
        retryable = code == AppErrorCode.PROJECT_SAVE_FAILED,
        technicalCause = error.message,
        stage = stage,
    )
}
